version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - 3000:3000
      - 27017:27017
    enviroment:
      NODE_ENV: ${NODE_ENV}